version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dinozoo_postgres
    restart: always
    environment:
      POSTGRES_DB: DinoZooTycoon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./helpers/database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: dinozoo_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/DinoZooTycoon
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  postgres_data: